# Generated by Django 2.1.7 on 2019-02-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited_speakers',
            field=models.TextField(blank=True),
        ),
    ]
